stages:
  - install
  - test
  - security
  - build

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

install:
  stage: install
  image: node:20-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
        - prisma/schema.prisma
    paths:
      - node_modules/
    policy: pull-push
  script:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    - pnpm exec prisma generate

lint:
  stage: test
  image: node:20-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
        - prisma/schema.prisma
    paths:
      - node_modules/
    policy: pull
  needs: [install]
  script:
    - npm install -g pnpm
    - pnpm lint

test:
  stage: test
  image: node:20-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
        - prisma/schema.prisma
    paths:
      - node_modules/
    policy: pull
  needs: [install]
  script:
    - npm install -g pnpm
    - pnpm test:cov
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 7 days

variables:
  SAST_EXCLUDED_PATHS: "coverage, node_modules, dist, test"
  SAST_EXCLUDED_ANALYZERS: "bandit, brakeman, flawfinder, gosec, kubesec, mobsf, phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs"
  SECRET_DETECTION_EXCLUDED_PATHS: "coverage, node_modules, dist"

sast:
  stage: security
  needs: []

secret_detection:
  stage: security
  needs: []

build:
  stage: build
  image: node:20-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
        - prisma/schema.prisma
    paths:
      - node_modules/
    policy: pull
  needs: [install]
  script:
    - npm install -g pnpm
    - pnpm build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  only:
    - main
